import "./ui/globals.css"
import { geistMono, geistSans } from "./ui/fonts";


export const metadata = {
  title: "Smart Stock | Athon Telecom",
  description: "Generated by create next app",
  icons: "/athonfav.png"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
