
import "./ui/globals.css"
import { geistMono, geistSans } from "./ui/fonts";
import { ThemeProvider } from "./ui/components/themeProvider";

export const metadata = {
  title: "Smart Stock | Athon Telecom",
  description: "Generated by create next app",
  icons: "/athonfav.png"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
